ministryofjustice/laa-crime-means-assessment

crime-means-assessment/src/main/resources/schemas/apiCreateInitialMeansAssessmentResponse.json, crime-means-assessment/src/main/resources/schemas/apiCreateIntialMeansAssessmentRequest.json, crime-means-assessment/src/main/resources/schemas/common/apiAddress.json, crime-means-assessment/src/main/resources/schemas/common/apiAssessmentDetail.json, crime-means-assessment/src/main/resources/schemas/common/apiFrequency.json, crime-means-assessment/src/main/resources/schemas/common/apiNewWorkReason.json, crime-means-assessment/src/main/resources/schemas/common/apiReviewType.json
Correcting schema ref fields. 
=> Correcting schema references

.git-crypt/keys/default/0/993EB4B7A226E98CFA8D1AEE40ADB407222C41CB.gpg
New collaborators:
222C41CB Aafreen Ansari (n) <aafreen.ansari@digital.justice.gov.uk>
Add new git-crypt collaborator
=> Add 1 git-crypt collaborator

crime-means-assessment/build.gradle, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/config/MaatApiOAuth2Client.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/controller/MeansAssessmentController.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/AssessmentCriteriaService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/MeansAssessmentService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/validation/CreateAssessmentValidator.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/validation/model/AssessmentValidationRequest.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/validation/model/AssessmentValidationResponse.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/validation/service/MeansAssessmentValidationService.java, crime-means-assessment/src/main/resources/application.yaml, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/service/AssessmentCriteriaServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-XXX)
=>  Enabling Security and cognito 

.circleci/config.yml, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/codeql-analysis.yml
Changes to codeql, circleci config etc after renaming master branch to main
=> Changes after renaming master branch to main

crime-means-assessment/src/main/resources/schemas/apiCreateMeansAssessmentRequest.json, crime-means-assessment/src/main/resources/schemas/apiCreateMeansAssessmentResponse.json
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-776)
Updated request and response json schema for full means assessment 
=> LASB-776|updated create means schema with full assessment fields

crime-means-assessment/build.gradle
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1035)
=> LASB-1035: Upgraded spring boot version.

crime-means-assessment/src/main/resources/application.yaml, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/config/MaatApiConfigurationTest.java, crime-means-assessment/src/test/resources/application.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1011)
=> LASB-1011 - Updated assessment API Routes

crime-means-assessment/src/main/resources/application.yaml, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/config/MaatApiConfigurationTest.java, crime-means-assessment/src/test/resources/application.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1011)
=> LASB-1011: Corrected the assessment api endpoint domain for MAAT API

.circleci/config.yml
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-975)
Updated-CircleCI-config-for-UAT
=> LASB-975-Updated-CircleCI-config-for-UAT

crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/builder/maatapi/MaatCourtDataAssessmentBuilder.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/common/Constants.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/AssessmentCriteriaService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/AssessmentSummaryService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/FullAssessmentAvailabilityService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/FullMeansAssessmentService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/InitMeansAssessmentService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/MaatCourtDataService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/MeansAssessmentService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/staticdata/enums/AssessmentType.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/staticdata/enums/CaseType.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/staticdata/enums/CurrentStatus.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/staticdata/enums/Frequency.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/staticdata/enums/FullAssessmentResult.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/staticdata/enums/InitAssessmentResult.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/staticdata/enums/ReviewType.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/staticdata/enums/WorkType.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/staticdata/repository/AssessmentCriteriaRepository.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/validation/service/MeansAssessmentValidationService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/validation/validator/InitAssessmentValidator.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/service/AssessmentCriteriaServiceTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/service/AssessmentSummaryServiceTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/staticdata/enums/CurrentStatusTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/staticdata/enums/FrequencyTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-XXX)
=> LASB-1055-Addressed Code Smells in Crime Means Assessment

.circleci/config.yml
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-976)
added circleci config for staging
=> LASB-976| added circleci config for staging

crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/validation/service/MeansAssessmentValidationService.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/service/MaatCourtDataServiceIntegrationTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/util/MaatWebClientIntegrationTestUtil.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/validation/service/MeansAssessmentValidationServiceIT.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/validation/service/MeansAssessmentValidationServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1033)
=> LASB-1033: Standardise web client usage.

crime-means-assessment/src/main/resources/application.yaml, crime-means-assessment/src/main/resources/logback.xml
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1094)
Fixed Sentry Logback misconfiguration issue. This should remove the errors present on start up and speed up application launch times. It will also mean that the Sentry specific settings in the application.yaml are correctly detected and applied.
=> Fixed Sentry Logback misconfiguration

crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/builder/maatapi/MaatCourtDataAssessmentBuilder.java, crime-means-assessment/src/main/resources/schemas/maatApiAssessmentRequest.json, crime-means-assessment/src/main/resources/schemas/maatApiAssessmentResponse.json
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1104)
Updated parameter names in Court Data API schema
=> LASB-1104: Updated parameter names in Court Data API schema

crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/AssessmentCriteriaService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/MeansAssessmentService.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1126)
Handled NPE for non required fields.
=> LASB-1126| handled NPE for non required fields

crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/service/MaatCourtDataServiceIntegrationTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/service/MaatCourtDataServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1069)
=> LASB-1069 - Added test cases for the create financial assessment history call

crime-means-assessment/src/main/resources/schemas/apiInitMeansAssessmentRequest.json
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-1139)
Schema updates to make reviewType as optional.
=> LASB-1139 - Schema updates to make reviewType as optional

crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/model/PostProcessing.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/model/UserSession.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/MeansAssessmentService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/PostProcessingMsgPublisherService.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/service/MeansAssessmentServiceTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/service/PostProcessingMsgPublisherServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-93)
Pass user session details to Post Processing.
=> LCAM-93|Pass user session details to Post Processing

crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/MaatCourtDataService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/MeansAssessmentService.java, crime-means-assessment/src/main/resources/application.yaml, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/service/MaatCourtDataServiceTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/service/MeansAssessmentServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-XXX)
=> Making Post Processing as a Sync process

crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/config/MaatApiOAuth2Client.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-155)
- Specified handling for connection timeouts in the Court Data API webClient
=> Ensure connection timeouts are retried

crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/MeansAssessmentService.java, crime-means-assessment/src/main/resources/schemas/common/apiAssessmentDetail.json
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-154)
Add id field to the AssessmentDetails object in line with DB
=> LCAM-154|Add id field to the AssessmentDetails object in line with DB

README.md
Modifying ReadMe to reflect  the CI/CD build status & license info
=> Modifying ReadMe to reflect  the CI/CD status

crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/builder/MeansAssessmentResponseBuilder.java
Added missing annotations causing startup failure.
=> Missing Annotations Causing Startup Failure

crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/service/FullAssessmentAvailabilityServiceTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/staticdata/enums/CurrentStatusTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-184)
Fixed sonar reported issues.
=> LCAM-184|Address sonar reported issues

crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/controller/MeansAssessmentControllerTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/controller/MeansAssessmentIntegrationTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/data/builder/TestModelDataBuilder.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-183)
=> LCAM 183 - Mean assessment integration test

crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/builder/MeansAssessmentSectionSummaryBuilder.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/controller/MeansAssessmentController.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/dto/maatcourtdata/ChildWeightings.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/AssessmentCriteriaChildWeightingService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/AssessmentCriteriaDetailService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/AssessmentCriteriaService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/MeansAssessmentService.java, crime-means-assessment/src/main/resources/schemas/common/apiAssessmentChildWeighting.json, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/builder/MeansAssessmentSectionSummaryBuilderTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/controller/MeansAssessmentControllerTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/data/builder/TestModelDataBuilder.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/service/MeansAssessmentServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-135)
Get child weightings as part of retrieving old assessment.
=> LCAM-135|Get child weightings as part of retrieving old assessment

crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/builder/MeansAssessmentSectionSummaryBuilder.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/controller/MeansAssessmentController.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/dto/maatcourtdata/FinancialAssessmentDTO.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/AssessmentCriteriaService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/MeansAssessmentService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/staticdata/enums/NewWorkReason.java, crime-means-assessment/src/main/resources/schemas/apiGetMeansAssessmentResponse.json, crime-means-assessment/src/main/resources/schemas/common/apiAssessmentDetail.json, crime-means-assessment/src/main/resources/schemas/common/apiAssessmentSectionSummary.json, crime-means-assessment/src/main/resources/schemas/common/apiFullMeansAssessment.json, crime-means-assessment/src/main/resources/schemas/common/apiIncomeEvidenceSummary.json, crime-means-assessment/src/main/resources/schemas/common/apiInitialMeansAssessment.json, crime-means-assessment/src/main/resources/schemas/common/apiNewWorkReason.json, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/builder/MeansAssessmentSectionSummaryBuilderTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/controller/MeansAssessmentControllerTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/controller/MeansAssessmentIntegrationTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/data/builder/TestModelDataBuilder.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/service/MeansAssessmentServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-61)
=> LCAM-61-New endpoint for get old assessment

crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/builder/MeansAssessmentSectionSummaryBuilder.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/FullMeansAssessmentService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/InitMeansAssessmentService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/MeansAssessmentService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/util/RoundingUtils.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/util/SortUtils.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/builder/MeansAssessmentSectionSummaryBuilderTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/data/builder/TestModelDataBuilder.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/service/MeansAssessmentServiceTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/util/RoundingUtilsTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/util/SortUtilsTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-244)
rounding full assessment amount fields.
=> LCAM-244|rounding full assessment amount fields

crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/builder/MeansAssessmentRequestDTOBuilder.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/dto/MeansAssessmentRequestDTO.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/validation/service/MeansAssessmentValidationService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/validation/validator/MeansAssessmentValidationProcessor.java, crime-means-assessment/src/main/resources/schemas/apiMeansAssessmentRequest.json, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/builder/MeansAssessmentRequestDTOBuilderTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/controller/MeansAssessmentIntegrationTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/data/builder/TestModelDataBuilder.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/validation/service/MeansAssessmentValidationServiceIT.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/validation/service/MeansAssessmentValidationServiceTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/validation/validator/MeansAssessmentValidationProcessorTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-161)
=> LCAM-161-Update Assessment Validation

crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/staticdata/enums/FullAssessmentResult.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-291)
=> LCAM-291-Full Assessment result

crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/FullMeansAssessmentService.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/service/FullMeansAssessmentServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-310)
=> LCAM-310-Removed INEL Status

crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/builder/MeansAssessmentSectionSummaryBuilder.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/MeansAssessmentService.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/builder/MeansAssessmentSectionSummaryBuilderTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/service/MeansAssessmentServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-370)
Populate fullAvailable field on the get assessment response.
=> LCAM-370|Populate fullAvailable field on the get assessment response

crime-means-assessment/src/main/resources/application.yaml
https://dsdmoj.atlassian.net/browse/LASB-1626 
=> Update Sentry Config to allow 5 % of the sample error

README.md
[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-386)
Updated readme
=> LCAM-386|updated readme

README.md
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-442)
Minor corrections in README
=> LCAM-442-minor-readme-corrections

crime-means-assessment/Dockerfile
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-499)
Docker base image update
=> LCAM-499| update docker base image

crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/dto/maatcourtdata/RepOrderDTO.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/data/builder/TestModelDataBuilder.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-533)
Update RepOrderDTO to match MAAT API.
=> LCAM-533|Update RepOrderDTO to match MAAT API

crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/staticdata/entity/IncomeEvidenceEntity.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/data/builder/TestModelDataBuilder.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-540)
Remove the redundant columns from static data table.
=> LCAM-540-Remove redundant fields in Entity

.circleci/config.yml, crime-means-assessment/build.gradle, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/config/ResourceServerConfiguration.java, crime-means-assessment/src/main/resources/application.yaml
[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-500)
Updated Snyk configuration so that the pipeline will fail if any critical vulnerabilities are discovered. Also fixed existing critical vulnerabilities.
=> LCAM 500 Enable Snyk in Pipeline

crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/FullMeansAssessmentService.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/service/FullMeansAssessmentServiceTest.java
Reverts ministryofjustice/laa-crime-means-assessment#282
=> Revert "Enabled processing of INEL Cases"

.circleci/config.yml, crime-means-assessment/.snyk
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-502)
- removed unused orbs
- added helm upgrade command
- consolidated build, scan and test job
- consolidated build, scan and push image job 
- updated snyk policy file to ignore h2 vuln
=> Lcam 502 refactor pipeline

.circleci/config.yml
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-638)
Updated circleci config and env variables to use short lived credentials
=> LCAM-638| updated circleci config to use short lived credentials

crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/controller/StatelessMeansAssessmentController.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/stateless/FrequencyAmount.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/stateless/Income.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/stateless/Outgoing.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/stateless/StatelessFullResult.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/stateless/StatelessInitialResult.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/staticdata/enums/stateless/AgeRange.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/staticdata/enums/stateless/IncomeType.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/staticdata/enums/stateless/OutgoingType.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/staticdata/enums/stateless/StatelessRequestType.java, crime-means-assessment/src/main/resources/schemas/stateless/statelessApiRequest.json, crime-means-assessment/src/main/resources/schemas/stateless/statelessApiResponse.json, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/controller/StatelessMeansAssessmentControllerTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/util/RequestBuilderUtils.java
https://dsdmoj.atlassian.net/browse/LCAM-690
This is still very much a work-in-progress, with the other tickets in this EPIC may well change inputs and outputs, however this basic structure appears to be complete for now.
=> LCAM-690 Stateless API controller with JSON

crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/controller/StatelessMeansAssessmentController.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/AssessmentCriteriaService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/BaseMeansAssessmentService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/CrownCourtEligibilityService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/EligibilityChecker.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/FullMeansAssessmentService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/InitMeansAssessmentService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/MeansAssessmentService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/stateless/Amount.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/stateless/DataAdapter.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/stateless/Income.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/stateless/Outgoing.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/stateless/StatelessAssessmentService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/stateless/StatelessFullResult.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/stateless/StatelessResult.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/staticdata/enums/stateless/AgeRange.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/controller/StatelessMeansAssessmentIntegrationTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/service/InitMeansAssessmentServiceTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/service/MeansAssessmentServiceTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/service/stateless/StatelessAssessmentServiceTest.java
https://dsdmoj.atlassian.net/browse/LCAM-691
Core of new Stateless API calling into existing CMA code
=> Lcam 691 stateless service

crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/validation/validator/MeansAssessmentValidationProcessor.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/controller/MeansAssessmentIntegrationTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/validation/validator/MeansAssessmentValidationProcessorTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-558)
=> LCAM-558|Remove the Modified by another user validation in CMA

crime-means-assessment/.snyk
[LCAM-859](https://dsdmoj.atlassian.net/browse/LCAM-859)
- Removed snyk ignore for Spring framework security 
[LCAM-859]: https://dsdmoj.atlassian.net/browse/LCAM-859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LCAM 859: Remove snyk ignore for Spring framework security 

crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/AssessmentCompletionService.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/service/AssessmentCompletionServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-2331)
=> LASB-2331: Hardship date completed error.

crime-means-assessment/build.gradle, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/cucumber/StatelessCucumberTest.java, crime-means-assessment/src/test/resources/cucumber.properties
Example cucumber JUnit 5 configuration.
=> LCAM-693: Update cucumber tests to run JUnit.

crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/stateless/StatelessAssessmentService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/stateless/StatelessFullResult.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/stateless/StatelessInitialResult.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/controller/StatelessMeansAssessmentControllerTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/cucumber/StatelessSteps.java
https://dsdmoj.atlassian.net/browse/LCAM-956
totalAggregatedIncome was expected in full assessment when it actually comes from initialAssessment.
=> LCAM-956 move totalAggregatedIncome to initial result

crime-means-assessment/build.gradle
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-XXX)
=> Fixed Snyk issues

crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/controller/StatelessMeansAssessmentController.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/BaseMeansAssessmentService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/stateless/StatelessAssessmentService.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/controller/StatelessMeansAssessmentControllerTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/service/stateless/StatelessAssessmentServiceTest.java
https://dsdmoj.atlassian.net/browse/LCAM-997
Refactor stateless service to be independent of the API
=> LCAM-997 stateless service refactor

crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/validation/validator/MeansAssessmentValidationProcessor.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1195)
Updated the logging to remove the request DTO and logging only the repId.
=> LCAM-1195|Limit the logging to rep id

crime-means-assessment/build.gradle, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/controller/MeansAssessmentController.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/MaatCourtDataService.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/MeansAssessmentService.java, crime-means-assessment/src/main/resources/schemas/maatapi/maatApiRollbackAssessment.json, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/controller/MeansAssessmentControllerTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/data/builder/TestModelDataBuilder.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/service/MaatCourtDataServiceTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/service/MeansAssessmentServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1096)
=> Rollback Endpoint

crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/controller/MeansAssessmentController.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/MeansAssessmentService.java, crime-means-assessment/src/main/resources/schemas/apiRollbackMeansAssessmentResponse.json, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/controller/MeansAssessmentControllerTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/service/MeansAssessmentServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1095)
=> Update rollback endpoint to PATCH

crime-means-assessment/build.gradle, crime-means-assessment/gradle/wrapper/gradle-wrapper.properties, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/builder/MaatCourtDataAssessmentBuilder.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/builder/MeansAssessmentResponseBuilder.java, crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/service/MeansAssessmentService.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/builder/MaatCourtDataAssessmentBuilderTest.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/data/builder/TestModelDataBuilder.java, crime-means-assessment/src/test/java/uk/gov/justice/laa/crime/meansassessment/service/MeansAssessmentServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1749)
Fixed schema mismatch between MAAT API and CMA for income evidence section. 
- Don’t forget to [run](https://github.com/ministryofjustice/laa-crimeapps-maat-functional-tests/actions/workflows/ExecuteUiTests.yaml) the MAAT functional test suite after deploying your changes to the DEV or TEST environments to ensure your changes haven’t broken any of the functional tests.
=> LCAM-1749-schema changes

crime-means-assessment/build.gradle
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1846)
Updated spring-security-core to version 6.4.6 to address the security vulnerability described here: https://security.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORKSECURITY-10185684
- Don’t forget to [run](https://github.com/ministryofjustice/laa-crimeapps-maat-functional-tests/actions/workflows/ExecuteUiTests.yaml) the MAAT functional test suite after deploying your changes to the DEV or TEST environments to ensure your changes haven’t broken any of the functional tests.
=> Update spring-security-core to fix vulnerability

helm_deploy/laa-crime-means-assessment/values-dev.yaml, helm_deploy/laa-crime-means-assessment/values-prod.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-4092)
Update MAAT Data API url to point to CP in Development environment.
=> LASB-4092|Update MAAT Data API url to point to CP in Dev

helm_deploy/laa-crime-means-assessment/values-prod.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-4092)
Updated MAAT API OAuth URL in PROD.
=> Update MAAT API OAuth URL

crime-means-assessment/build.gradle
Upgraded dependencies suggested by Dependabot in one PR.
- Don’t forget to [run](https://github.com/ministryofjustice/laa-crimeapps-maat-functional-tests/actions/workflows/ExecuteUiTests.yaml) the MAAT functional test suite after deploying your changes to the DEV or TEST environments to ensure your changes haven’t broken any of the functional tests.
=> Dependency Upgrades
